### ISSUE TITLE
I cannot build with VSCode

### ISSUE THREAD

**Issue by n67t1cq** [JonnyHaystack/XCube#1]
Hello, I want to build XCube with VSCode, What tools do you use?

I got I many MSB3073 errors,and couldn't build with VSCode in Win 10.

**Comment by JonnyHaystack** [comment]
Don't know what you mean by building with VS Code. You need CMake and ARM GCC installed, and you need to set up the Pico SDK with the modifications needed for https://github.com/Ryzee119/tusb_xinput
To get that library to work iirc I had to clone pico SDK, go into the tinyusb submodule inside the Pico SDK, checkout to the latest commit, and apply the changes described in the README.
